### ISSUE TITLE
DefaultRevisionMetadata.getRevisionDate does not work in 2.0

### ISSUE THREAD

**Issue by britter** [spring-projects/spring-data-envers#112]
After updating to Spring Data Envers 2.0.3 from 1.1.9 I get thew following error:

```
java.time.DateTimeException: Unable to obtain LocalDate from TemporalAccessor: 2018-01-30T07:37:59.787Z of type java.time.Instant
	at java.time.LocalDate.from(LocalDate.java:368) ~[na:1.8.0_144]
	at java.time.LocalDateTime.from(LocalDateTime.java:456) ~[na:1.8.0_144]
	at org.springframework.data.envers.repository.support.DefaultRevisionMetadata.getRevisionDate(DefaultRevisionMetadata.java:54) ~[spring-data-envers-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.data.history.Revision.getRevisionDate(Revision.java:86) ~[spring-data-commons-2.0.2.RELEASE.jar:2.0.2.RELEASE]
```

This is because `DefaultRevisionMetadata.getRevisionDate()` creates a `LocalDateTime` from an instant using `LocalDateTime.from(TemporalAccessor)` instead of `LocalDateTime.ofInstant(Instant, ZoneId)`

**Comment by schauder** [comment]
Related: https://jira.spring.io/browse/DATACMNS-1251
