### ISSUE TITLE
No suitable constructor found to match the given arguments: Object

### ISSUE THREAD

**Issue by RizziCR** [spring-projects/spring-data-envers#39]
Hi,

i try to use spring-data-envers, but i get the following exception on application start.
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'IActiveProfileRepository': Invocation of init method failed; nested exception is java.lang.IllegalStateException: No suitable constructor found on class org.springframework.data.envers.repository.support.EnversRevisionRepositoryImpl to match the given arguments: [Ljava.lang.Object;@1ac2af7f
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	... 37 common frames omitted

Caused by: java.lang.IllegalStateException: No suitable constructor found on class org.springframework.data.envers.repository.support.EnversRevisionRepositoryImpl to match the given arguments: [Ljava.lang.Object;@1ac2af7f
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getTargetRepositoryViaReflection(RepositoryFactorySupport.java:338) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:91) ~[spring-data-jpa-1.9.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:71) ~[spring-data-jpa-1.9.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:185) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.envers.repository.support.EnversRevisionRepositoryFactoryBean$RevisionRepositoryFactory.getRepository(EnversRevisionRepositoryFactoryBean.java:129) ~[spring-data-envers-0.3.0.BUILD-SNAPSHOT.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:251) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:237) ~[spring-data-commons-1.11.0.RELEASE.jar:na]
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:92) ~[spring-data-jpa-1.9.0.RELEASE.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	... 47 common frames omitted
```
The repository:
```java
	@Repository
	public interface IActiveProfileRepository extends RevisionRepository<ActiveProfile, String, Integer>, PagingAndSortingRepository<ActiveProfile, String>, JpaSpecificationExecutor<ActiveProfile> {
```

JpaConfig:
```java
	@EnableJpaRepositories(basePackages = {"xxx.core.service", "xxx.core.dao.jpa"}, repositoryFactoryBeanClass = EnversRevisionRepositoryFactoryBean.class)
```

I try with 0.2.0 and with 0.3.0 both with the same result.

**Comment by RizziCR** [comment]
After some testing. It's looks like that the RevisionRepository interface is ignored. It doesn't mater if its extends my repository or not. If i remove it after 'extends', i got the same error.

**Comment by igler** [comment]
Have submitted a bug (https://jira.spring.io/browse/DATACMNS-767) as I am facing the same issues when upgrading to Gosling-RELEASE.

**Comment by igler** [comment]
See https://github.com/spring-projects/spring-data-envers/pull/40

**Comment by RizziCR** [comment]
Thanks
